version: '3'
services:
    php:
        build:
            context: .
            dockerfile: ./Dockerfile_dev
            args:
                HOST_UID: 1000
                HOST_GID: 1000
        command: php-fpm
        user: 1000:1000
        ports:
            - 9000:9000
        volumes:
            - ./:/app:cached
            # Cannot use this because of the directory rights are forced for root user
            #- /app/var/
        environment:
            PHP_IDE_CONFIG: "serverName=app.localhost"
            # Eg. in GCP environment just set this environment variable
            # to your k8s configuration.
            #
            # https://symfony.com/doc/current/deployment/proxies.html
            TRUSTED_PROXIES: "127.0.0.1,REMOTE_ADDR"

    nginx:
        build:
            context: ./docker/nginx/
            args:
                HOST_UID: 1000
                HOST_GID: 1000
        depends_on:
            - php
        ports:
            - 8000:80
        volumes:
            - ./:/app:cached
            # Cannot use this because of the directory rights are forced for root user
            #- /app/var/
